FROM node:18.14

RUN mkdir -p /usr/src/app


WORKDIR /usr/src/app


COPY package*.json ./

RUN npm install
RUN npm install -g nodemon
RUN npm install moment --save




COPY . .



EXPOSE 6000

CMD ["sh", "-c", "npm i && npm run dev"]

